"""Function-calling agent loop.

The loop is synchronous and SDK-agnostic: it depends on a `generate` callable
that accepts a normalized contents representation and returns an
`AgentResponse`. `app.core.gemini.RealGeminiClient` adapts this to the
google-genai SDK; tests inject a fake.

Loop:
  1. Build role-aware system prompt from the live snapshot.
  2. Send the conversation (with the role's tool declarations) to Gemini.
  3. If Gemini returns function calls, execute each via the tool registry
     (server-side role guard), append the function responses, and repeat.
  4. Stop when Gemini returns a final text answer, or the max iteration count
     is reached (return a graceful fallback).
"""
from __future__ import annotations

from dataclasses import dataclass, field
import logging
from typing import Any

from ..core.config import settings
from ..models.chat import Message, ToolEvent
from ..models.roles import Role
from ..models.state import StadiumSnapshot
from ..tools.handlers import ToolContext
from ..tools.registry import ToolRegistry
from .prompt import build_system_prompt

logger = logging.getLogger(__name__)




@dataclass
class FunctionCall:
    """Represents a function call generated by the Gemini model."""

    name: str
    args: dict[str, Any]
    id: str = ""


@dataclass
class AgentResponse:
    """Represents a structured response from the Gemini client, containing text or tool calls."""

    text: str | None = None
    function_calls: list[FunctionCall] = field(default_factory=list)


# A normalized "part" is one of:
#   {"text": str}
#   {"function_call": {"name": str, "args": dict, "id": str}}
#   {"function_response": {"name": str, "response": dict}}
# A content item is {"role": "user"|"model", "parts": [part, ...]}.
Contents = list[dict[str, Any]]


class LLMClientProtocol:
    """Protocol for the LLM API client interface."""

    def generate(
        self,
        system_instruction: str,
        contents: Contents,
        tool_declarations: list[Any],
        model: str,
    ) -> AgentResponse:  # pragma: no cover - interface only
        """Generates a response from the LLM.

        Args:
            system_instruction: The instruction governing the model's behavior.
            contents: The current conversation history including tool calls/responses.
            tool_declarations: A list of functions/tools the model is allowed to call.
            model: The model identifier to query.

        Returns:
            The response from the agent.

        """
        raise NotImplementedError


@dataclass
class AgentResult:
    """Represents the final result of running the agent loop."""

    reply: str
    tool_events: list[ToolEvent]
    snapshot_summary: str


class Agent:
    """Coordinates the function-calling agent loop, executing tools and building prompt context."""

    def __init__(
        self,
        client: LLMClientProtocol,
        registry: ToolRegistry,
        ctx: ToolContext,
    ) -> None:
        """Initializes the Agent.

        Args:
            client: The LLM API client protocol.
            registry: The tool registry to lookup and execute tools.
            ctx: The tool execution context.

        """
        self.client = client
        self.registry = registry
        self.ctx = ctx

    def run(
        self,
        message: str,
        role: Role,
        history: list[Message] | None = None,
        language: str = "en",
        max_iterations: int | None = None,
    ) -> AgentResult:
        """Runs the main agent loop.

        Sends the user query and history to Gemini, executes any requested tools,
        and continues until a final answer is returned or iteration limit is reached.

        Args:
            message: The current user message string.
            role: The user's role (e.g. Organizer, Volunteer, Fan).
            history: Optional conversation history.
            language: The preferred response language.
            max_iterations: Optional override for the max tool iteration count.

        Returns:
            The final AgentResult containing the response, tool events, and snapshot.

        """
        snapshot: StadiumSnapshot = self.ctx.snapshot()
        if self._is_unsafe(message):
            return AgentResult(
                reply="I cannot fulfill this request. For your safety and security, operations are restricted to tournament guidelines.",
                tool_events=[],
                snapshot_summary=snapshot.summary(),
            )

        system_instruction = build_system_prompt(role, snapshot, language)
        tool_declarations = self.registry.declarations_for_role(role)
        max_iters = max_iterations or settings.agent_max_tool_iterations

        contents: Contents = self._seed_history(history)
        contents.append({"role": "user", "parts": [{"text": message}]})

        events: list[ToolEvent] = []
        for _ in range(max_iters):
            try:
                response = self.client.generate(
                    system_instruction=system_instruction,
                    contents=contents,
                    tool_declarations=tool_declarations,
                    model=settings.gemini_model,
                )
            except Exception as exc:
                logger.exception("Gemini API call failed: %s", exc)
                return AgentResult(
                    reply=f"I encountered an API error: {exc!s}. Here is the live stadium snapshot: {snapshot.summary()}",
                    tool_events=events,
                    snapshot_summary=snapshot.summary(),
                )
            if not response.function_calls:
                return AgentResult(
                    reply=response.text or "",
                    tool_events=events,
                    snapshot_summary=snapshot.summary(),
                )
            # record the model's function-call turn
            model_parts: list[dict[str, Any]] = []
            for fc in response.function_calls:
                model_parts.append({"function_call": {"name": fc.name, "args": fc.args, "id": fc.id}})
            contents.append({"role": "model", "parts": model_parts})

            # execute each call and append responses
            response_parts: list[dict[str, Any]] = []
            for fc in response.function_calls:
                if not self.registry.is_allowed(fc.name, role):
                    result = {"error": f"PermissionDenied: Role '{role.value}' is not authorized to call '{fc.name}'."}
                else:
                    result = self.registry.execute(fc.name, fc.args, role, self.ctx)
                error = isinstance(result, dict) and "error" in result
                events.append(ToolEvent(name=fc.name, args=fc.args or {}, result=result, error=error))
                response_parts.append({"function_response": {"name": fc.name, "response": result}})
            contents.append({"role": "user", "parts": response_parts})

        # exceeded max iterations
        return AgentResult(
            reply=(
                "I'm working on that but couldn't complete the lookup in time. "
                "Here's what I know so far based on live stadium state: "
                + snapshot.summary()
            ),
            tool_events=events,
            snapshot_summary=snapshot.summary(),
        )

    def _seed_history(self, history: list[Message] | None) -> Contents:
        """Seeds the Gemini contents list from the provided conversation history.

        Args:
            history: Optional conversation history.

        Returns:
            A list of dictionary parts normalized for the Gemini API.

        """
        contents: Contents = []
        for m in history or []:
            if not m.content:
                continue
            contents.append({"role": m.role, "parts": [{"text": m.content}]})
        return contents

    def _is_unsafe(self, message: str) -> bool:
        """Performs input safety scan checking length, jailbreaks, PII, and env exfiltration.
        Robust against pluralization, spacing variations, casing bypasses, and PII/env bypasses.

        Args:
            message: The user's query string.

        Returns:
            True if unsafe, False otherwise.

        """
        if len(message) >= settings.agent_max_message_chars:
            return True

        import re
        import unicodedata

        # 1. Casing & Unicode Homoglyph Normalization
        # Decompose characters (e.g. convert full-width characters to standard, separate accents)
        nfkd_form = unicodedata.normalize('NFKD', message)
        # Strip combining diacritics (accents) to normalize characters like 'è' to 'e'
        normalized_msg = "".join(c for c in nfkd_form if not unicodedata.combining(c)).lower()

        # 2. Jailbreak keywords with regexes to handle:
        #   - Pluralization (optional 's' or 'es')
        #   - Spacing variations (multiple spaces, tabs, newlines, hyphens, underscores)
        #   - Word boundaries (\b)
        
        # Replace punctuation/delimiters with spaces for clean keyword token checking
        cleaned_for_jailbreak = re.sub(r'[^a-z0-9\s]', ' ', normalized_msg)
        cleaned_words = " ".join(cleaned_for_jailbreak.split())

        # Define robust regex patterns for jailbreaks (checked against cleaned_words)
        jailbreak_patterns = [
            r"\bignore\s+previous\s+instructions?\b",
            r"\bdump\s+system\s+prompts?\b",
            r"\byou\s+are\s+now\s+in\s+developer\s+mode\b",
            r"\bexecute\s+all\s+tools?\b",
            r"\bsystem\s+prompts?\b",
            r"\bjail\s*breaks?\b",
            r"\boverride\s+constraints?\b",
        ]
        
        if any(re.search(pat, cleaned_words) for pat in jailbreak_patterns):
            return True

        # 3. PII patterns (robust against separator variations: dots, underscores, slashes, spaces)
        # SSN: 3 digits, 2 digits, 4 digits with optional non-alphanumeric separators (excluding letters)
        # CC: 13 to 16 digits, with optional non-alphanumeric separators between them
        ssn_pattern = r"\b\d{3}[\s\W_]*\d{2}[\s\W_]*\d{4}\b"
        cc_pattern = r"\b(?:\d[\s\W_]*?){13,16}\b"
        
        if re.search(ssn_pattern, message) or re.search(cc_pattern, message):
            return True

        # 4. Env exfiltration patterns (robust against spacing, different delimiters, missing curly braces)
        # Matches: os.environ, os.getenv, process.env, with arbitrary spacing/separators
        env_exfil_patterns = [
            r"\bos\s*[\s\W_]*\s*(?:environ|getenv)\b",
            r"\bprocess\s*[\s\W_]*\s*env\b",
        ]
        if any(re.search(pat, normalized_msg) for pat in env_exfil_patterns):
            return True

        # Matches standalone 'environ' or 'getenv' keywords (covers getattr(os, 'environ'))
        if re.search(r"\benviron\b", normalized_msg) or re.search(r"\bgetenv\b", normalized_msg):
            return True

        # Matches: $VAR, ${VAR}, $(VAR), %VAR% (preventing false positives on digits/currency)
        env_var_patterns = [
            r"\$(?:\{[A-Za-z_][A-Za-z0-9_]*\}|\([A-Za-z_][A-Za-z0-9_]*\)|[A-Za-z_][A-Za-z0-9_]*)",
            r"%[A-Za-z_][A-Za-z0-9_]*%",
        ]
        if any(re.search(pat, message) for pat in env_var_patterns):
            return True

        return False

